// ui/src/components/MessageContainer.svelte
<script>
  import { messages } from "../store";
  import { onMount, afterUpdate } from "svelte";

  let messageContainer;
  let previousMessageCount = 0;

  afterUpdate(() => {
    if ($messages && $messages.length > previousMessageCount) {
      messageContainer.scrollTop = messageContainer.scrollHeight;
      previousMessageCount = $messages.length;
    }
  });
</script>

<div id="message-container" class="flex-grow overflow-y-auto pr-2" bind:this={messageContainer}>
  {#if $messages !== null}
    {#each $messages as message}
      <div class="flex items-start space-x-3 mt-4">
        {#if message.from_StartifyAI}
          <img
            src="/assets/StartifyAI-avatar.png"
            alt="StartifyAI's Avatar"
            class="avatar rounded-full flex-shrink-0"
            style="width: 40px; height: 40px;"
          />
        {:else}
          <img
            src="/assets/user-avatar.png"
            alt="User's Avatar"
            class="avatar rounded-full flex-shrink-0"
            style="width: 40px; height: 40px;"
          />
        {/if}

        <div class="flex flex-col w-full">
          <p class="text-xs text-gray-400 sender-name">
            {message.from_StartifyAI ? "StartifyAI" : "You"}
            <span class="timestamp"
              >{new Date(message.timestamp).toLocaleTimeString()}</span
            >
          </p>
          {#if message.from_StartifyAI && message.message.startsWith('{')}
            <div
              class="bg-slate-800 p-2 rounded w-full mr-4"
              contenteditable="false"
            >
            {@html `<strong>Here's my step-by-step plan:</strong>`}
            <br><br>
            {#if JSON.parse(message.message)}
              {#each Object.entries(JSON.parse(message.message)) as [step, description]}
                <input type="checkbox" id="step-{step}" disabled />
                <label for="step-{step}"><strong>Step {step}</strong>: {description}</label>
                <br><br>
              {/each}
            {/if}
            </div>
          {:else if /https?:\/\/[^\s]+/.test(message.message)}
            <div
              class="bg-slate-800 p-2 rounded w-full mr-4"
              contenteditable="false"
            >
              {@html message.message.replace(/(https?:\/\/[^\s]+)/g, '<u><a href="$1" target="_blank" style="font-weight: bold;">$1</a></u>')}
            </div>
          {:else}
            <div
              class="bg-slate-800 p-2 rounded w-full mr-4"
              contenteditable="false"
              bind:innerHTML={message.message}
            ></div>
          {/if}
        </div>
      </div>
    {/each}
  {/if}
</div>

<style>
  .sender-name {
    margin-bottom: 4px;
    display: flex;
    align-items: baseline;
  }

  .timestamp {
    margin-left: 8px;
    font-size: smaller;
    color: #aaa;
  }

  #message-container {
    height: 390px;
    overflow-y: auto;
  }

  #message-container::-webkit-scrollbar {
    width: 4px;
  }

  #message-container::-webkit-scrollbar-track {
    background: #020617;
    border-radius: 10px;
  }

  #message-container::-webkit-scrollbar-thumb {
    background: #4337c9;
    border-radius: 10px;
  }

  input[type="checkbox"] {
    appearance: none;
    -webkit-appearance: none;
    -moz-appearance: none;
    -ms-appearance: none;
    -o-appearance: none;
    display: inline-block;
    width: 16px;
    height: 16px;
    border: 2px solid #4337c9;
    border-radius: 4px;
    margin-right: 8px;
    position: relative;
    top: 3px;
  }
</style>

// vite-ui/src/components/dashboard/MessageContainer.tsx
import { useAppStore } from "@/hooks/store/useAppStore";
import useAppMessages from "@/hooks/useAppMessages";
import { useInterval } from "@/hooks/useInterval";
import { Fragment, useEffect, useRef, useState } from "react";

const MessageContainer = () => {
	const messageContainerRef = useRef<HTMLDivElement>(null);
	const [previousMessageCount, setPreviousMessageCount] = useState<number>(0);
	const { getMessages } = useAppMessages();
	const { messages, setMessages } = useAppStore();

	const fetchMessages = async () => {
		const messages = await getMessages();
		if (messages.length > 0) {
			setMessages(messages);
		}
	};

	useInterval(fetchMessages, 1000);

	useEffect(() => {
		if (messages && messages.length > previousMessageCount) {
			messageContainerRef.current?.scrollTo({
				top: messageContainerRef.current.scrollHeight,
				behavior: "smooth",
			});
			setPreviousMessageCount(messages.length);
		}
	}, [messages]);

	return (
		<div className="flex-grow overflow-y-scroll pr-2" ref={messageContainerRef}>
			{messages && messages.length > 0 ? (
				messages.map((msg, idx) => (
					<div key={idx} className="flex items-start space-x-3 mt-4">
						{msg.from_StartifyAI ? (
							<img src="/logo.png" alt="StartifyAI's Avatar" className="avatar rounded-full flex-shrink-0 w-[40px] h-[40px]" />
						) : (
							<img src="/user-avatar.png" alt="User's Avatar" className="avatar rounded-full flex-shrink-0 w-[40px] h-[40px]" />
						)}
						<div className="flex flex-col w-full">
							<p className="text-xs text-gray-400 sender-name">
								{msg.from_StartifyAI ? "StartifyAI" : "You"}
								<span className="timestamp">{new Date(msg.timestamp).toLocaleTimeString()}</span>
							</p>
							{msg.from_StartifyAI && msg.message.startsWith("{") ? (
								<div className="bg-slate-800 p-2 rounded w-full mr-4" contentEditable="false">
									<strong>Here's my step-by-step plan:</strong>
									<br />
									<br />
									{Object.entries(JSON.parse(msg.message)).map(([step, description]) => (
										<Fragment key={step}>
											<input type="checkbox" id={`step-${step}`} disabled />
											<label htmlFor={`step-${step}`}>
												<strong>Step {step}</strong>: {description as string}
											</label>
											<br />
											<br />
										</Fragment>
									))}
								</div>
							) : new RegExp("https?://[^\\s]+").test(msg.message) ? (
								<div
									className="bg-slate-800 p-2 rounded w-full mr-4"
									contentEditable="false"
									dangerouslySetInnerHTML={{ __html: msg.message.replace(/(https?:\/\/[^\s]+)/g, '<u><a href="$1" target="_blank" style="font-weight: bold;">$1</a></u>') }}
								/>
							) : (
								<div className="bg-slate-800 p-2 rounded w-full mr-4" contentEditable="false" dangerouslySetInnerHTML={{ __html: msg.message }} />
							)}
						</div>
					</div>
				))
			) : (
				<div>
					<p className="text-center text-gray-400">No messages yet</p>
				</div>
			)}
		</div>
	);
};

export default MessageContainer;
